import React, { useEffect, useState } from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { Ionicons } from "@expo/vector-icons";
import { LoadingState } from "../components/AppUi";
import { useAuth } from "../context/AuthContext";
import { LoginScreen } from "../screens/auth/LoginScreen";
import { OnboardingIntroScreen } from "../screens/auth/OnboardingIntroScreen";
import { OnboardingVisualMenusScreen } from "../screens/auth/OnboardingVisualMenusScreen";
import { RegisterScreen } from "../screens/auth/RegisterScreen";
import { ProfileScreen } from "../screens/common/ProfileScreen";
import { ManagerDashboardScreen } from "../screens/manager/ManagerDashboardScreen";
import { ManagerPlatesScreen } from "../screens/manager/ManagerPlatesScreen";
import { ManagerRestaurantScreen } from "../screens/manager/ManagerRestaurantScreen";
import { FeedScreen } from "../screens/user/FeedScreen";
import { HomeScreen } from "../screens/user/HomeScreen";
import { PlateDetailsScreen } from "../screens/user/PlateDetailsScreen";
import { RestaurantDetailsScreen } from "../screens/user/RestaurantDetailsScreen";
import { ReviewCameraScreen } from "../screens/user/ReviewCameraScreen";
import { ReviewCreateScreen } from "../screens/user/ReviewCreateScreen";
import { getHasSeenOnboarding, setHasSeenOnboarding } from "../services/onboardingStorage";
import { managerColors } from "../screens/manager/ManagerUi";
